apiVersion: apps/v1
kind: Deployment
metadata:
  name: afhfhg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: afhfhg
  template:
    metadata:
      labels:
        app: afhfhg
    spec:
      containers:
      - image: okteto.dev/afhfhg:latest
        name: afhfhg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "8ec630dc-fd66-4a8e-9e8a-fafbda69e5b1"
        - name: Vless_Path
          value: "/ghjmguju4fdg"
        - name: Vmess_UUID
          value: "8ec630dc-fd66-4a8e-9e8a-fafbda69e5b1"
        - name: Vmess_Path
          value: "/ghjmguju4fdg"
        - name: Share_Path
          value: "/v2link"
